global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend-api"
    metrics_path: /metrics/
    static_configs:
      - targets: ["backend-api:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
